# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Algolia' do

pod 'Masonry'
pod 'AFNetworking'

end

target 'AlgoliaTests' do

end

target 'AlgoliaUITests' do

end
